// Copies Preact and htm into public/vendor/ as plain ES modules the browser loads directly.
//
// Why vendored rather than a CDN: the hub's CSP is `script-src 'self'`, so every script must come
// from this origin. Why no bundler: htm's tagged templates need no transpiling, so the source in
// public/ is the code that runs — the same property the CLI has, and one less thing to rot.
//
// The one edit: preact's hooks bundle imports from the bare specifier "preact", which a browser
// cannot resolve. Rewriting it to a relative path avoids needing an import map, which would have
// to be an inline <script> and so would need loosening the CSP.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "public", "vendor");
mkdirSync(out, { recursive: true });

const copy = (from, to, patch = (s) => s) => {
  const src = patch(readFileSync(join(here, "..", "node_modules", from), "utf8"));
  writeFileSync(join(out, to), src);
  console.log(`  ${to.padEnd(20)} ${src.length} bytes`);
};

copy("preact/dist/preact.module.js", "preact.js");
copy("preact/hooks/dist/hooks.module.js", "hooks.js", (s) =>
  s.replace(/(from\s*["'])preact(["'])/g, "$1./preact.js$2"),
);
copy("htm/dist/htm.module.js", "htm.js");

// One entry point, so pages import a single thing and the wiring lives in one place.
writeFileSync(
  join(out, "index.js"),
  `// Generated by scripts/vendor.mjs — do not edit. Run \`pnpm -C apps/api vendor\` to refresh.
import { h } from "./preact.js";
import htm from "./htm.js";

export { render } from "./preact.js";
export { useState, useEffect, useCallback, useRef } from "./hooks.js";
export const html = htm.bind(h);
`,
);
console.log("  index.js");
